version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./consignment-service
    environment:
      MICRO_ADDRESS: ".50051"
      MICRO_REGISTRY: "mmdns"
      DB_HOST: "datastore:27017"
    ports:
      - 50051:50051

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50052
    environment:
      MICRO_ADDRESS: ".50051"
      MICRO_REGISTRY: "mmdns"
      DB_HOST: "datastore:27017"

  datastore:
    image: mongo
    ports:
      - 27017:27017
